# Generated by Django 5.2.7 on 2026-04-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "processed"],
                        name="payments_st_event_t_6c60d1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeAcademyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement_descriptor",
                    models.CharField(
                        blank=True,
                        help_text="Appears on athlete's card statement (max 22 chars).",
                        max_length=22,
                    ),
                ),
                ("default_currency", models.CharField(default="usd", max_length=3)),
                ("is_onboarded", models.BooleanField(default=False)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "unique_together": {("academy",)},
            },
        ),
    ]
