# Generated by Django 5.2.7 on 2026-04-08 07:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
        ("athletes", "0005_athleteprofile_stripe_customer_id"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripeacademyconfig",
            name="is_onboarded",
        ),
        migrations.AddField(
            model_name="stripeacademyconfig",
            name="charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripeacademyconfig",
            name="details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripeacademyconfig",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripeacademyconfig",
            name="payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stripeacademyconfig",
            name="stripe_connect_account_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION", "Subscription"),
                            ("SEMINAR", "Seminar"),
                            ("ONE_TIME_PLAN", "One-time plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gross amount the athlete paid (e.g. 50.00).",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="FlowRoll's commission (application_fee_amount / 100).",
                        max_digits=10,
                    ),
                ),
                (
                    "academy_net",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount transferred to the academy's Express account (before Stripe's own fees).",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("stripe_invoice_url", models.URLField(blank=True)),
                ("extra_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="athletes.athleteprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["athlete", "status"],
                        name="payments_pa_athlete_b8023c_idx",
                    ),
                    models.Index(
                        fields=["academy", "status"],
                        name="payments_pa_academy_de5bbc_idx",
                    ),
                    models.Index(
                        fields=["payment_type", "status"],
                        name="payments_pa_payment_05904b_idx",
                    ),
                ],
            },
        ),
    ]
