from django.db import models

from core.mixins import TimestampMixin, TenantMixin


class WeightClass(models.Model):
    """
    A competitive weight division used for matchmaking.
    Not academy-specific — shared across the platform.
    """

    class Gender(models.TextChoices):
        MALE = "M", "Male"
        FEMALE = "F", "Female"
        OPEN = "O", "Open"

    name = models.CharField(max_length=50)
    min_weight = models.FloatField(help_text="Minimum weight in kg (inclusive).")
    max_weight = models.FloatField(help_text="Maximum weight in kg (inclusive).")
    gender = models.CharField(max_length=1, choices=Gender.choices, default=Gender.OPEN)

    class Meta:
        ordering = ["gender", "min_weight"]
        unique_together = ("name", "gender")

    def __str__(self):
        return f"{self.name} ({self.gender}) {self.min_weight}–{self.max_weight} kg"


class TimerPreset(TenantMixin, TimestampMixin):
    """
    A reusable timer configuration for live tatami sessions.
    Supports IBJJF, ADCC, and custom positional sparring presets.
    """

    class Format(models.TextChoices):
        IBJJF = "IBJJF", "IBJJF"
        ADCC = "ADCC", "ADCC"
        POSITIONAL = "POSITIONAL", "Positional Sparring"
        CUSTOM = "CUSTOM", "Custom"

    name = models.CharField(max_length=80)
    format = models.CharField(max_length=20, choices=Format.choices, default=Format.CUSTOM)
    round_duration_seconds = models.PositiveIntegerField(
        default=300, help_text="Duration of each round in seconds."
    )
    rest_duration_seconds = models.PositiveIntegerField(
        default=60, help_text="Rest period between rounds in seconds."
    )
    overtime_seconds = models.PositiveIntegerField(
        default=0, help_text="Overtime duration; 0 means no overtime."
    )
    rounds = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ("academy", "name")

    def __str__(self):
        return f"{self.name} ({self.format})"


class TimerSession(TimestampMixin):
    """
    Runtime state of a live timer.
    Designed to be polled via REST or pushed via WebSocket.
    """

    class Status(models.TextChoices):
        IDLE = "IDLE", "Idle"
        RUNNING = "RUNNING", "Running"
        PAUSED = "PAUSED", "Paused"
        FINISHED = "FINISHED", "Finished"

    preset = models.ForeignKey(
        TimerPreset,
        on_delete=models.CASCADE,
        related_name="sessions",
    )
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.IDLE)
    current_round = models.PositiveIntegerField(default=1)
    started_at = models.DateTimeField(null=True, blank=True)
    paused_at = models.DateTimeField(null=True, blank=True)
    elapsed_seconds = models.PositiveIntegerField(
        default=0,
        help_text="Seconds elapsed when the timer was last paused.",
    )

    def __str__(self):
        return f"Session({self.preset.name}) — {self.status}"


class Matchup(TenantMixin, TimestampMixin):
    """
    A single pairing of two athletes generated by the matchmaking algorithm.
    """

    class MatchFormat(models.TextChoices):
        TOURNAMENT = "TOURNAMENT", "Tournament (bracket)"
        SURVIVAL = "SURVIVAL", "Survival (king of the mat)"

    class MatchStatus(models.TextChoices):
        PENDING = "PENDING", "Pending"
        IN_PROGRESS = "IN_PROGRESS", "In Progress"
        COMPLETED = "COMPLETED", "Completed"
        CANCELLED = "CANCELLED", "Cancelled"

    athlete_a = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.CASCADE,
        related_name="matchups_as_a",
    )
    athlete_b = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.CASCADE,
        related_name="matchups_as_b",
    )
    weight_class = models.ForeignKey(
        WeightClass,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="matchups",
    )
    match_format = models.CharField(
        max_length=15, choices=MatchFormat.choices, default=MatchFormat.TOURNAMENT
    )
    round_number = models.PositiveIntegerField(default=1)
    status = models.CharField(
        max_length=15, choices=MatchStatus.choices, default=MatchStatus.PENDING
    )
    winner = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="matchups_won",
    )

    class Meta:
        indexes = [models.Index(fields=["academy", "match_format", "status"])]

    def __str__(self):
        return f"{self.athlete_a} vs {self.athlete_b} [{self.match_format}]"
