# Generated by Django 5.2.7 on 2026-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academy",
            options={
                "ordering": ["name"],
                "verbose_name": "Academy",
                "verbose_name_plural": "Academies",
            },
        ),
        migrations.AddField(
            model_name="academy",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="academy",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="academy",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="academy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="academy",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="academy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="academy",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name="academy",
            index=models.Index(
                fields=["is_active"], name="academies_a_is_acti_9dc37f_idx"
            ),
        ),
    ]
