# Generated by Django 5.2.7 on 2026-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Belt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Belt progression order, 1=white, 5=black"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
