# Generated by Django 5.2.7 on 2026-04-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
        ("membership", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_customer_id", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("SEMINAR", "Seminar Registration"),
                            ("DOJO_TAB_CREDIT", "Dojo Tab Credit"),
                            ("ONE_TIME_CLASS", "One-time Class"),
                            ("MERCHANDISE", "Merchandise"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "seminar_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_payments",
                        to="membership.seminarregistration",
                    ),
                ),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="membership.stripecustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_payment_method_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        choices=[
                            ("CARD", "Card"),
                            ("ACH_DEBIT", "ACH Debit"),
                            ("SEPA_DEBIT", "SEPA Debit"),
                        ],
                        default="CARD",
                        max_length=20,
                    ),
                ),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("brand", models.CharField(blank=True, max_length=20)),
                ("exp_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("exp_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="membership.stripecustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_subscription_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "Incomplete"),
                            ("INCOMPLETE_EXPIRED", "Incomplete Expired"),
                            ("TRIALING", "Trialing"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELED", "Canceled"),
                            ("UNPAID", "Unpaid"),
                            ("PAUSED", "Paused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="membership.stripecustomer",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_subscription",
                        to="membership.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="membership__stripe__20b7c3_idx",
                    ),
                    models.Index(
                        fields=["event_type", "processed"],
                        name="membership__event_t_935474_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stripecustomer",
            index=models.Index(
                fields=["stripe_customer_id"], name="membership__stripe__18db11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripepayment",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="membership__stripe__bf416d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stripepayment",
            index=models.Index(fields=["status"], name="membership__status_f63075_idx"),
        ),
        migrations.AddIndex(
            model_name="stripepayment",
            index=models.Index(
                fields=["payment_type"], name="membership__payment_76fa2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripepaymentmethod",
            index=models.Index(
                fields=["stripe_payment_method_id"],
                name="membership__stripe__11c788_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stripepaymentmethod",
            index=models.Index(
                fields=["stripe_customer", "is_default"],
                name="membership__stripe__0a3a56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stripesubscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="membership__stripe__ee6e35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripesubscription",
            index=models.Index(fields=["status"], name="membership__status_186eac_idx"),
        ),
    ]
