# Generated by Django 5.2.7 on 2026-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojotabtransaction",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="seminarregistration",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
