# Generated by Django 5.2.7 on 2026-04-07 19:12

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
        (
            "membership",
            "0002_stripecustomer_stripepayment_stripepaymentmethod_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeConnectedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_account_id", models.CharField(max_length=255, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("EXPRESS", "Express"),
                            ("STANDARD", "Standard"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="EXPRESS",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Setup"),
                            ("RESTRICTED", "Restricted"),
                            ("ENABLED", "Enabled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("details_submitted", models.BooleanField(default=False)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("business_url", models.URLField(blank=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("onboarding_url", models.URLField(blank=True)),
                ("dashboard_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketplaceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION", "Subscription Payment"),
                            ("ONE_TIME", "One-time Payment"),
                            ("SEMINAR", "Seminar Registration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stripe_transfer_id", models.CharField(blank=True, max_length=255)),
                (
                    "stripe_application_fee_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("customer_invoice_url", models.URLField(blank=True)),
                ("platform_invoice_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "seminar_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_transactions",
                        to="membership.seminarregistration",
                    ),
                ),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_transactions",
                        to="membership.stripecustomer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketplace_transactions",
                        to="membership.subscription",
                    ),
                ),
                (
                    "connected_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="membership.stripeconnectedaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AcademyEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_platform_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_stripe_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_net",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("subscription_count", models.PositiveIntegerField(default=0)),
                ("one_time_count", models.PositiveIntegerField(default=0)),
                ("seminar_count", models.PositiveIntegerField(default=0)),
                ("refund_count", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "connected_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="membership.stripeconnectedaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="PlatformCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("HYBRID", "Hybrid (Fixed + Percentage)"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "percentage_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1000"),
                        help_text="Percentage rate (0.1000 = 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed amount per transaction",
                        max_digits=8,
                    ),
                ),
                (
                    "min_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum commission per transaction",
                        max_digits=8,
                    ),
                ),
                (
                    "max_commission",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum commission per transaction (null = no limit)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("effective_from", models.DateField(default=datetime.date.today)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["academy", "effective_from"],
                        name="membership__academy_1a9896_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="membership__is_acti_f6ef84_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stripeconnectedaccount",
            index=models.Index(
                fields=["stripe_account_id"], name="membership__stripe__78061f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripeconnectedaccount",
            index=models.Index(fields=["status"], name="membership__status_ae9698_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplacetransaction",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="membership__stripe__45edcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacetransaction",
            index=models.Index(
                fields=["connected_account", "status"],
                name="membership__connect_5ef02c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacetransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="membership__transac_aec4d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academyearnings",
            index=models.Index(
                fields=["academy", "year", "month"],
                name="membership__academy_2db38e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academyearnings",
            index=models.Index(
                fields=["connected_account", "year", "month"],
                name="membership__connect_f7b9bd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academyearnings",
            unique_together={("connected_account", "year", "month")},
        ),
    ]
