# Generated by Django 5.2.7 on 2026-04-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
        ("membership", "0003_stripeconnectedaccount_marketplacetransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcommission",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_commissions",
                to="academies.academy",
            ),
        ),
    ]
