# Generated by Django 5.2.7 on 2026-04-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_dojotabtransaction_stripe_payment_intent_id_and_more"),
        ("membership", "0004_alter_platformcommission_academy"),
    ]

    operations = []
