"""
Competition and tournament management models.

Tournaments are academy-scoped events with divisions (by belt/weight),
participants, and matchups. The bracket is generated by TournamentService
and stored as TournamentMatch records.
"""

from django.db import models

from core.mixins import TenantMixin, TimestampMixin


class Tournament(TenantMixin, TimestampMixin, models.Model):
    """A BJJ tournament hosted by an academy."""

    class Status(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        OPEN = "OPEN", "Open for Registration"
        IN_PROGRESS = "IN_PROGRESS", "In Progress"
        COMPLETED = "COMPLETED", "Completed"
        CANCELLED = "CANCELLED", "Cancelled"

    class Format(models.TextChoices):
        BRACKET = "BRACKET", "Single-Elimination Bracket"
        ROUND_ROBIN = "ROUND_ROBIN", "Round Robin"

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    date = models.DateField()
    location = models.CharField(max_length=300, blank=True)
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.DRAFT
    )
    format = models.CharField(
        max_length=20, choices=Format.choices, default=Format.BRACKET
    )
    max_participants = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Leave blank for unlimited participants.",
    )

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.name} ({self.date})"


class TournamentDivision(TimestampMixin, models.Model):
    """
    A competition category within a tournament, defined by belt range and weight.

    Examples: Blue/Purple Belt Under-76 kg, White Belt Open Weight.
    """

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="divisions"
    )
    name = models.CharField(max_length=200)
    belt_min = models.CharField(
        max_length=10,
        help_text="Minimum belt required to enter this division.",
    )
    belt_max = models.CharField(
        max_length=10,
        help_text="Maximum belt allowed in this division.",
    )
    weight_min = models.FloatField(
        null=True, blank=True, help_text="Minimum weight in kg (inclusive)."
    )
    weight_max = models.FloatField(
        null=True, blank=True, help_text="Maximum weight in kg (inclusive)."
    )

    class Meta:
        unique_together = ("tournament", "name")
        ordering = ["name"]

    def __str__(self):
        return f"{self.tournament.name} — {self.name}"


class TournamentParticipant(TimestampMixin, models.Model):
    """An athlete registered for a specific division in a tournament."""

    class RegistrationStatus(models.TextChoices):
        PENDING = "PENDING", "Pending"
        CONFIRMED = "CONFIRMED", "Confirmed"
        WITHDRAWN = "WITHDRAWN", "Withdrawn"
        CHECKED_IN = "CHECKED_IN", "Checked In"

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="participants"
    )
    division = models.ForeignKey(
        TournamentDivision,
        on_delete=models.CASCADE,
        related_name="participants",
        null=True,
        blank=True,
    )
    athlete = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.CASCADE,
        related_name="tournament_entries",
    )
    status = models.CharField(
        max_length=20,
        choices=RegistrationStatus.choices,
        default=RegistrationStatus.PENDING,
    )
    # Snapshot of belt/weight at registration time
    belt_at_registration = models.CharField(max_length=10, blank=True)
    weight_at_registration = models.FloatField(null=True, blank=True)
    seed = models.PositiveIntegerField(
        null=True, blank=True, help_text="Seeding position assigned before bracket generation."
    )

    class Meta:
        unique_together = ("tournament", "athlete")
        ordering = ["seed", "athlete__user__username"]

    def __str__(self):
        return f"{self.athlete} in {self.tournament.name}"


class TournamentMatch(TimestampMixin, models.Model):
    """
    A single match within a tournament bracket or round-robin schedule.

    Athlete slots can be NULL before the bracket is fully populated
    (e.g. a match waiting for a previous round to finish).
    """

    tournament = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, related_name="matches"
    )
    division = models.ForeignKey(
        TournamentDivision,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="matches",
    )
    round_number = models.PositiveSmallIntegerField(default=1)
    athlete_a = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tournament_matches_as_a",
    )
    athlete_b = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tournament_matches_as_b",
    )
    winner = models.ForeignKey(
        "athletes.AthleteProfile",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tournament_match_wins",
    )
    score_a = models.SmallIntegerField(default=0)
    score_b = models.SmallIntegerField(default=0)
    is_finished = models.BooleanField(default=False)
    notes = models.CharField(max_length=300, blank=True)

    class Meta:
        ordering = ["round_number", "id"]

    def __str__(self):
        return (
            f"R{self.round_number}: {self.athlete_a} vs {self.athlete_b} "
            f"({self.tournament.name})"
        )
