# Generated by Django 5.2.7 on 2025-11-09 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Belt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Belt progression order, 1=white, 5=black"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True)),
                ("difficulty", models.IntegerField(default=1)),
                ("image_url", models.URLField(blank=True)),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Source of the data, e.g., 'BlackBeltWiki'",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_belt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="techniques",
                        to="techniques.belt",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="techniques", to="techniques.techniquecategory"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField()),
                ("source", models.CharField(default="YouTube", max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="techniques.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["technique", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition_type",
                    models.CharField(
                        choices=[
                            ("chain", "Chain"),
                            ("counter", "Counter"),
                            ("escape", "Escape"),
                            ("setup", "Setup"),
                        ],
                        default="chain",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "from_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads_to",
                        to="techniques.technique",
                    ),
                ),
                (
                    "to_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comes_from",
                        to="techniques.technique",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_technique", "to_technique")},
            },
        ),
        migrations.CreateModel(
            name="TechniqueVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="techniques.technique",
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="variations",
                        to="techniques.techniquevideo",
                    ),
                ),
            ],
            options={
                "unique_together": {("technique", "name")},
            },
        ),
    ]
