# Generated by Django 5.2.7 on 2025-10-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Belt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Orden de progresión del cinturón, 1=white, 5=black"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TechniqueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("difficulty", models.IntegerField(default=1)),
                ("image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                (
                    "min_belt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="techniques",
                        to="techniques.belt",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="techniques", to="techniques.techniquecategory"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="TechniqueVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="techniques.technique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechniqueFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("probability", models.FloatField(default=1.0)),
                (
                    "from_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads_to",
                        to="techniques.technique",
                    ),
                ),
                (
                    "to_technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comes_from",
                        to="techniques.technique",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_technique", "to_technique")},
            },
        ),
    ]
