# Generated by Django 5.2.7 on 2025-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techniques", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techniquecategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
