# Generated by Django 5.2.7 on 2025-10-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='updated_at',
        ),
    ]
