# Generated by Django 5.2.7 on 2025-10-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0002_remove_technique_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquecategory',
            name='parent',
        ),
    ]
