# Generated by Django 5.2.7 on 2025-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techniques", "0002_alter_techniquecategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="belt",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="techniquevideo",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
