# Generated by Django 5.2.7 on 2026-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techniques", "0003_belt_description_alter_techniquevideo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="min_belt",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("brown", "Brown"),
                    ("black", "Black"),
                ],
                default="white",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Belt",
        ),
    ]
