# Generated by Django 5.2.7 on 2026-03-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techniques", "0004_alter_technique_min_belt_delete_belt"),
    ]

    operations = [
        migrations.AddField(
            model_name="techniquevideo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="techniquevideo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
