# Generated by Django 5.2.7 on 2026-03-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        ("athletes", "0003_athleteprofile_coach_athleteprofile_mat_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("IBJJF", "IBJJF"),
                            ("ADCC", "ADCC"),
                            ("POSITIONAL", "Positional Sparring"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                (
                    "round_duration_seconds",
                    models.PositiveIntegerField(
                        default=300, help_text="Duration of each round in seconds."
                    ),
                ),
                (
                    "rest_duration_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Rest period between rounds in seconds."
                    ),
                ),
                (
                    "overtime_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Overtime duration; 0 means no overtime."
                    ),
                ),
                ("rounds", models.PositiveIntegerField(default=1)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
            ],
            options={
                "unique_together": {("academy", "name")},
            },
        ),
        migrations.CreateModel(
            name="TimerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("FINISHED", "Finished"),
                        ],
                        default="IDLE",
                        max_length=10,
                    ),
                ),
                ("current_round", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "elapsed_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Seconds elapsed when the timer was last paused.",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tatami.timerpreset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeightClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "min_weight",
                    models.FloatField(help_text="Minimum weight in kg (inclusive)."),
                ),
                (
                    "max_weight",
                    models.FloatField(help_text="Maximum weight in kg (inclusive)."),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Open")],
                        default="O",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "ordering": ["gender", "min_weight"],
                "unique_together": {("name", "gender")},
            },
        ),
        migrations.CreateModel(
            name="Matchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_format",
                    models.CharField(
                        choices=[
                            ("TOURNAMENT", "Tournament (bracket)"),
                            ("SURVIVAL", "Survival (king of the mat)"),
                        ],
                        default="TOURNAMENT",
                        max_length=15,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "athlete_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchups_as_a",
                        to="athletes.athleteprofile",
                    ),
                ),
                (
                    "athlete_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchups_as_b",
                        to="athletes.athleteprofile",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchups_won",
                        to="athletes.athleteprofile",
                    ),
                ),
                (
                    "weight_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchups",
                        to="tatami.weightclass",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["academy", "match_format", "status"],
                        name="tatami_matc_academy_e8d8e8_idx",
                    )
                ],
            },
        ),
    ]
