# Generated by Django 5.2.7 on 2026-03-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tatami", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matchup",
            options={"ordering": ["round_number", "-created_at"]},
        ),
    ]
