# Generated by Django 5.2.7 on 2026-03-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="openmatsession",
            new_name="community_o_academy_cb4a48_idx",
            old_name="community_openmatsession_academy_event_date_idx",
        ),
        migrations.AlterField(
            model_name="openmatsession",
            name="academy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="academies.academy",
            ),
        ),
    ]
