# Generated by Django 5.2.7 on 2025-10-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Guard', 'Guard'), ('Sweep', 'Sweep'), ('Submission', 'Submission'), ('Transition', 'Transition')], max_length=100)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='core.belt')),
            ],
        ),
        migrations.CreateModel(
            name='Finalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalizations', to='core.technique')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('from_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transitions', to='core.technique')),
                ('to_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='core.technique')),
            ],
        ),
    ]
