# Generated by Django 5.2.7 on 2026-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_totpdevice_last_otp_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="last_otp_counter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
