# Generated by Django 5.2.7 on 2026-03-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        ("athletes", "0003_athleteprofile_coach_athleteprofile_mat_hours_and_more"),
        ("attendance", "0002_initial"),
        ("techniques", "0004_alter_technique_min_belt_delete_belt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparringNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opponent_name", models.CharField(blank=True, max_length=100)),
                ("session_date", models.DateField()),
                (
                    "submission_log",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of submissions attempted/achieved.",
                    ),
                ),
                (
                    "performance_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Great"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sparring_notes",
                        to="athletes.athleteprofile",
                    ),
                ),
                (
                    "training_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sparring_notes",
                        to="attendance.trainingclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="VideoLibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("YOUTUBE", "YouTube"),
                            ("VIMEO", "Vimeo"),
                            ("OTHER", "Other"),
                        ],
                        default="YOUTUBE",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public (all members)"),
                            ("PROFESSORS", "Professors only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("belt_level", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "academy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="academies.academy",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="library_videos",
                        to="techniques.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassTechniqueJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("professor_notes", models.TextField(blank=True)),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="techniques.technique",
                    ),
                ),
                (
                    "training_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_journals",
                        to="attendance.trainingclass",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("training_class", "technique")},
            },
        ),
    ]
