# Generated by Django 5.2.7 on 2026-03-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("PROFESSOR", "Professor")],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                (
                    "belt",
                    models.CharField(
                        choices=[
                            ("WHITE", "Blanco"),
                            ("BLUE", "Azul"),
                            ("PURPLE", "Morado"),
                            ("BROWN", "Marrón"),
                            ("BLACK", "Negro"),
                        ],
                        default="WHITE",
                        max_length=20,
                    ),
                ),
                ("stripes", models.IntegerField(default=0)),
                (
                    "academy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athletes",
                        to="academies.academy",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
