# Generated by Django 5.2.7 on 2026-03-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteprofile",
            name="belt",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("brown", "Brown"),
                    ("black", "Black"),
                ],
                default="WHITE",
                max_length=20,
            ),
        ),
    ]
