# Generated by Django 5.2.7 on 2026-03-17 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0001_initial"),
        ("athletes", "0002_alter_athleteprofile_belt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct instructor; enables ancestry-tree traversal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="athletes.athleteprofile",
            ),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="mat_hours",
            field=models.FloatField(
                default=0.0,
                help_text="Cumulative mat hours derived from attendance check-ins.",
            ),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Body weight in kilograms, used for matchmaking.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="athleteprofile",
            name="belt",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("brown", "Brown"),
                    ("black", "Black"),
                ],
                default="white",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="athleteprofile",
            index=models.Index(
                fields=["academy", "belt"], name="athletes_at_academy_e61da4_idx"
            ),
        ),
    ]
