# Generated by Django 5.2.7 on 2026-03-30 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0003_athleteprofile_coach_athleteprofile_mat_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteprofile",
            name="stripes",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="athleteprofile",
            name="weight",
            field=models.FloatField(
                blank=True,
                help_text="Body weight in kilograms, used for matchmaking.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
    ]
