# Generated by Django 5.2.7 on 2026-04-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0004_add_stripes_weight_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
