# Generated by Django 5.2.7 on 2026-04-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0005_athleteprofile_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="belt_awarded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the athlete received their current belt. Used to compute months_at_belt for promotion eligibility.",
                null=True,
            ),
        ),
    ]
