# Generated by Django 5.2.7 on 2026-04-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_academy_options_academy_country_and_more"),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="academy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="academies.academy",
            ),
        ),
    ]
