# Generated by Django 5.2.7 on 2026-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("CHECKIN_MILESTONE", "Check-in Milestone"),
                    ("BELT_PROMOTION", "Belt Promotion"),
                    ("STRIPE_AWARD", "Stripe Awarded"),
                    ("ACHIEVEMENT_UNLOCKED", "Achievement Unlocked"),
                    ("CLASS_REMINDER", "Class Reminder"),
                    ("PAYMENT_SUCCEEDED", "Payment Succeeded"),
                    ("PAYMENT_FAILED", "Payment Failed"),
                    ("PROMOTION_READY", "Promotion Ready"),
                ],
                max_length=30,
            ),
        ),
    ]
