# Generated by Django 5.2.7 on 2026-03-31 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingclass",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=60, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
